

from  dremio/dremio-oss
expose 9047
expose 31010
expose 45678



# from ubuntu 


# RUN apt update -y
# RUN apt-get  install default-jre -y 
# RUN apt-get default-jdk  -y
# RUN sudo yum localinstall dremio-19.0.0.rpm -y


# RUN java -version 
# RUN javac --version

# entrypoint ["bash", "-c"]